# Generated by Django 5.0.4 on 2024-04-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
