# Generated by Django 5.0.4 on 2024-04-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titan', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('image', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('titan2', models.CharField(blank=True, max_length=100)),
                ('description2', models.TextField(blank=True, max_length=10000)),
            ],
        ),
    ]
