# Generated by Django 5.0.4 on 2024-04-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_media', '0002_detail_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_media',
            name='titan',
        ),
        migrations.RemoveField(
            model_name='detail_media',
            name='titan2',
        ),
        migrations.AddField(
            model_name='detail_media',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail_media',
            name='title2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
