# Generated by Django 5.0.4 on 2024-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_media', '0003_remove_detail_media_titan_remove_detail_media_titan2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_media',
            name='Memory',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='detail_media',
            name='Physical_characteristics',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='detail_media',
            name='Sensors',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='detail_media',
            name='audio_and_video',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='detail_media',
            name='battry',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='detail_media',
            name='camera',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='detail_media',
            name='cpu',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='detail_media',
            name='display',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='detail_media',
            name='os',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='detail_media',
            name='ram',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
