# Generated by Django 5.0.4 on 2024-04-17 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novin_media', '0004_detail_media_memory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail_media',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'جرئیات موبایل ها و محصولات'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'موبایل های و محصولات'},
        ),
    ]
