# Generated by Django 5.0.4 on 2024-04-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novin_media', '0005_alter_detail_media_options_alter_media_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail_media',
            options={'verbose_name': 'نوین', 'verbose_name_plural': 'جرئیات موبایل ها و محصولات'},
        ),
    ]
