# Generated by Django 5.0.4 on 2024-05-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=100)),
                ('inventory', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name': 'نوین پارت',
                'verbose_name_plural': 'لیست محصولات',
            },
        ),
    ]
