# Generated by Django 5.0.4 on 2024-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
