# Generated by Django 5.0.4 on 2024-05-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_part', '0002_alter_part_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.IntegerField(),
        ),
    ]
