# Generated by Django 5.0.4 on 2024-05-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_part', '0003_alter_part_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField()),
                ('user_text1', models.TextField()),
                ('user_text2', models.TextField()),
            ],
        ),
    ]
