# Generated by Django 5.0.4 on 2024-05-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novin_part', '0004_userinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
