# Generated by Django 5.0.4 on 2024-05-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_part', '0006_userinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='user_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='user_text1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='user_text2',
            field=models.TextField(blank=True),
        ),
    ]
