# Generated by Django 5.0.4 on 2024-04-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_details_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_details',
            name='writer_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
