# Generated by Django 5.0.4 on 2024-04-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_details_writer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'وبلاگ ها'},
        ),
        migrations.AlterModelOptions(
            name='blog_details',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'جزئات وبلاگ ها'},
        ),
        migrations.AlterModelOptions(
            name='blog_tags',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'تگ ها'},
        ),
    ]
