# Generated by Django 5.0.4 on 2024-04-17 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_options_alter_blog_details_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'پست ها', 'verbose_name_plural': 'وبلاگ ها'},
        ),
        migrations.AlterModelOptions(
            name='blog_details',
            options={'verbose_name': 'جرئیات', 'verbose_name_plural': 'جرئیات وبلاگ ها'},
        ),
        migrations.AlterModelOptions(
            name='blog_tags',
            options={'verbose_name': 'تگ ها', 'verbose_name_plural': 'تگ ها'},
        ),
    ]
