# Generated by Django 5.0.4 on 2024-04-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='description3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='description4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='title2',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='title3',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='title4',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
