# Generated by Django 5.0.4 on 2024-04-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_academy', '0002_period_description2_period_description3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField()),
                ('user_text1', models.TextField()),
                ('user_text2', models.TextField()),
                ('user_text3', models.TextField()),
            ],
            options={
                'verbose_name': 'نوین فیکس',
                'verbose_name_plural': 'درخواست های دوره ها',
            },
        ),
    ]
