# Generated by Django 5.0.4 on 2024-04-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novin_academy', '0003_userinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='user_text3',
        ),
    ]
