# Generated by Django 5.0.4 on 2024-04-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_academy', '0004_remove_userinput_user_text3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinput',
            options={'verbose_name': 'نوین فیکس', 'verbose_name_plural': 'درخواست های نوین '},
        ),
        migrations.AddField(
            model_name='userinput',
            name='user_text3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
