# Generated by Django 5.0.4 on 2024-04-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novin_academy', '0005_alter_userinput_options_userinput_user_text3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='user_text3',
        ),
    ]
