# Generated by Django 5.0.4 on 2024-04-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novin_academy', '0006_remove_userinput_user_text3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinput',
            options={'verbose_name': 'نوین آکادمی', 'verbose_name_plural': 'درخواست های نوین '},
        ),
    ]
