# Generated by Django 5.0.4 on 2024-04-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novin_academy', '0007_alter_userinput_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'نوین آکادمی', 'verbose_name_plural': 'دوره ها '},
        ),
    ]
