# Generated by Django 5.0.4 on 2024-04-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_academy', '0009_period_image1_period_image2_period_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='video_description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='video_description2',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='video_description3',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
