# Generated by Django 5.0.4 on 2024-04-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logo',
        ),
    ]
