# Generated by Django 5.0.4 on 2024-04-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_image_slider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_slider',
            options={},
        ),
    ]
