# Generated by Django 5.0.4 on 2024-04-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_image_slider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='team_image',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'عکس های تیم'},
        ),
    ]
