# Generated by Django 5.0.4 on 2024-04-17 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_class_options_alter_customers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'دوره ها', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'نظرات', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='image_slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'عکس های صفحه اصلی'},
        ),
        migrations.AlterModelOptions(
            name='team_image',
            options={'verbose_name': 'تیم', 'verbose_name_plural': 'عکس های تیم'},
        ),
    ]
