# Generated by Django 5.0.4 on 2024-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_slider',
            name='link',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
