# Generated by Django 5.0.4 on 2024-04-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_image_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_slider',
            name='link',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image_slider',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image_slider',
            name='text2',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image_slider',
            name='text3',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='image_slider',
            name='text4',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
