# Generated by Django 5.0.4 on 2024-04-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_fix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyFormModel',
        ),
    ]
