# Generated by Django 5.0.4 on 2024-04-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_fix', '0002_userinput_delete_myformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='user_text1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
