# Generated by Django 5.0.4 on 2024-04-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_fix', '0003_userinput_user_text1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='user_text2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinput',
            name='user_text3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
