# Generated by Django 5.0.4 on 2024-04-17 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novin_fix', '0004_userinput_user_text2_userinput_user_text3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinput',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'درخواست های نوین فیکس'},
        ),
    ]
