# Generated by Django 5.0.4 on 2024-04-17 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novin_fix', '0005_alter_userinput_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinput',
            options={'verbose_name': 'نوین فیکس', 'verbose_name_plural': 'درخواست های نوین فیکس'},
        ),
    ]
