# Generated by Django 5.0.4 on 2024-05-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novin_fix', '0006_alter_userinput_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='user',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
